### ISSUE TITLE
Use current Atom syntax theme, background-color, font, font-size, line-height, etc.

### ISSUE THREAD

**Issue by acondiff** [jsmecham/atom-terminal-tab#11]
A more consistent look with the current Atom syntax theme would keep things more appealing not to mention color differentiation would help as well.

**Comment by jsmecham** [comment]
Agreed. I am meaning to look at the best options for this. I'd prefer not to have to bundle a bunch of different themes and be able to pick up the colors from the theme, but I haven't had time to really work on this yet.

**Comment by acondiff** [comment]
I am happy to take a stab at it if I could get it working. (See issue #14)

**Comment by acondiff** [comment]
Check out this PR... https://github.com/jsmecham/atom-terminal-tab/pull/16

**Comment by dcalhoun** [comment]
Super excited for this! Should this issue be closed now that #16 has been merged?

@jsmecham do you plan to publish another release in the near future? Thanks!

**Comment by jsmecham** [comment]
I've released [v0.3.0](https://github.com/jsmecham/atom-terminal-tab/tree/v0.3.0) with support for matching theme colors. Font size is not included, but planned.
