### ISSUE TITLE
Random artifacts

### ISSUE THREAD

**Issue by rzjnzk** [jsmecham/atom-terminal-tab#113]
![image](https://user-images.githubusercontent.com/29923471/56846911-1428ee80-6914-11e9-8154-74f1f23ed844.png)

As can be seen in the above image, random artifacts sometimes appear in the terminal; notice the white dots and lines. I have not verified whether this is the case with 'Match Theme' unchecked, but in my instance, it certainly is the case when it is checked. This is especially common when Unicode symbols are displayed in the terminal. Though also results in a session where only alphanumeric characters are displayed. The artifacts seem to increase over time and are absent in a freshly opened terminal tab.

Update: 

These artifacts disappear when the width of the terminal window is altered. Adding `\$(resize > /dev/null 2>&1)` to my prompt variable `${PS1}` appeared to have no effect, whereas physically altering the width of the terminal completely cleared the artifacts.

**Comment by austincondiff** [comment]
I have this issue on occasion as well. I believe it is an Xterm.js issue but I have not verified that.

**Comment by jsmecham** [comment]
Please let me know if you see this with the latest release (0.6.0) which uses Xterm.js 4.2.0.
