### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by sauki8** [jsmecham/atom-terminal-tab#118]
And then, rebuild failed, when i rebuild package (image attached).
![rebuildfailed](https://user-images.githubusercontent.com/12002432/61926654-b00dd900-af9b-11e9-9ab7-04faab452582.jpg)

**Comment by xavierfoucrier** [comment]
@jsmecham I have the same issue... package should be updated.

**Comment by andrespagella** [comment]
Same problem here. I'm using Atom 1.39.1 x64

**Comment by itsN0ll** [comment]
same problem, also reinstalling does not help
Atom 1.39.1 x64
Macos 10.14.6

**Comment by xavierfoucrier** [comment]
@jsmecham up please :sunglasses:

**Comment by blubs** [comment]
> same problem, also reinstalling does not help
> ![image](https://user-images.githubusercontent.com/24757705/62422937-b143b200-b6cf-11e9-80fc-f5308c83c350.png)
> Atom 1.39.1 x64
> Macos 10.14.6

I was able to rebuild terminal-tab on my machine.
Note: I have Anaconda installed, which defaults Python to 3.7, and I was initializing Anaconda in my ~/.bash_profile, thus Atom was attempting to rebuild the terminal-tab package with Python 3.7.

As listed in the screenshot posted by @itsN0ll, rebuilding it requires "Python >= 2.5.0 & < 3.0.0".

So all I had to do was to remove the conda initialization from my bash_profile, launch Atom (which now points to Python 2.7), and rebuild the package.

Then I re-added the Anaconda init to my bash_profile, and all is good.

**Comment by xavierfoucrier** [comment]
@blubs thanks for the feedback, I will try to do the same on Windows. :smile:

**Comment by xavierfoucrier** [comment]
@jsmecham up please :smiley:

**Comment by the-j0k3r** [comment]
See https://github.com/jsmecham/atom-terminal-tab/pull/120

you can change those files as in PR in your installed package fo terminal tab in `.atom/packages` and then delete the node_modules and do.

`apm i`

**Comment by jsmecham** [comment]
Please try with the latest version (0.6.0).

**Comment by xavierfoucrier** [comment]
@jsmecham it work just fine with the latest! Thanks for the fix :wink:
