### ISSUE TITLE
Fails to open on Atom 1.41.0

### ISSUE THREAD

**Issue by fenhl** [jsmecham/atom-terminal-tab#123]
I just updated Atom to 1.41.0 and now the package seems to be broken. It worked fine before the update. Using the ⇧⌘T shortcut doesn't do anything anymore, and no relevant commands appear in the ⇧⌘P menu.

**Comment by jsmecham** [comment]
I just published 0.6.0, could you try again and let me know if it is still broken?

**Comment by fenhl** [comment]
Seems to be fixed, thank you!

**Comment by fenhl** [comment]
Unfortunately, this bug has reappeared, this time on Windows.
