### ISSUE TITLE
Shortcut key problem.

### ISSUE THREAD

**Issue by maktoobgar** [jsmecham/atom-terminal-tab#129]
hi.
there is a problem with cmd-shift-T shortcut operation.
it is not overwritted on Atom default cmd-shift-T operation (opens previous closed pages).
also it is better for us to bind our shortcut keys (if it's possible).
except this... i have a perfect package on my atom IDE.
thank you for creating it.

**Comment by ghost** [comment]
I have the same problem.

**Comment by yacc143** [comment]
Agree, same problem for me here, Atom 1.48.0 on Ubuntu 18.04

**Comment by nelson6e65** [comment]
I replaced with `f7`: https://github.com/jsmecham/atom-terminal-tab/issues/135#issuecomment-748556519

BTW, this folk looks good: https://github.com/samuelivarsson/atom-iv-terminal

Give it a try. Also, offers copy & paste (https://github.com/samuelivarsson/atom-iv-terminal/issues/1#issuecomment-748558208)
