### ISSUE TITLE
Whitespace characters in text selection

### ISSUE THREAD

**Issue by emersion** [jsmecham/atom-terminal-tab#13]
When selecting multiple lines of text, there are many space characters before end of lines.

**Comment by jsmecham** [comment]
Hi @emerson, I'm not seeing this on my machine. Can you elaborate?

**Comment by emersion** [comment]
Let's say you want to `cat` a file to copy-paste two lines from it:

![](http://i.imgur.com/YsjL6uX.png)

Then you paste, there are many spaces, and tabs are replaced by spaces:

![](http://i.imgur.com/aiCykNS.png)

This is because the terminal outputs extra space characters and replaces tabs by spaces:

![](http://i.imgur.com/dy1TeBb.png)

It is fixable by:
* Do not outputting extra spaces at end of lines, or use the `user-select` CSS property to prevent it from being selected
* Do not replace tabs by spaces, and use the `tab-width` CSS property if needed

**Comment by jsmecham** [comment]
Please test again with the latest release (0.5.0). If it is still a problem, feel free to reopen this issue.
