### ISSUE TITLE
Package fails in Atom 1.18

### ISSUE THREAD

**Issue by acondiff** [jsmecham/atom-terminal-tab#14]
I get the following error when attempting to activate.

```
Failed to require the main module of 'atom-terminal-tab' because it requires one or more incompatible native modules (node-pty).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

Running `apm rebuild` and restarting Atom does not seem to do anything.

**Comment by jsmecham** [comment]
Try running `ape-beta rebuild` instead.

**Comment by acondiff** [comment]
Haha should have known to do that, but unfortunately that didn't work either.

**Comment by acondiff** [comment]
Just updated stable Atom and it breaks there now as well. (changed title)

**Comment by acondiff** [comment]
I believe this is not a problem any longer. I was possibly a problem related to my local environment.
