### ISSUE TITLE
Environment variables not setting

### ISSUE THREAD

**Issue by jaydenseric** [jsmecham/atom-terminal-tab#23]
For some reason environment variables are not being set when using packages like [`zoo`](https://github.com/jsonmaur/zoo) or [`dotenv-cli`](https://github.com/entropitor/dotenv-cli).

They work fine in the Mac Terminal and [`platformio-atom-ide-terminal`](https://github.com/platformio/platformio-atom-ide-terminal).

**Comment by jsmecham** [comment]
Hi @jaydenseric, can you retest this on the latest version of terminal tab and let me know if it is still an issue? Thanks!

**Comment by jaydenseric** [comment]
I have switched from Atom to VS Code, but best of luck 🙂
