### ISSUE TITLE
Installing “atom-terminal-tab@0.2.2” failed in atom 1.19.0

### ISSUE THREAD

**Issue by TechiePriyaRanjan** [jsmecham/atom-terminal-tab#26]
I'm unable install it in my atom, every time I'm installing it it's giving the same error.

 node-pty@0.6.10 install C:\Users\PRIYAR~1\AppData\Local\Temp\apm-install-dir-117726-16708-zbisyb.hgw5o5stt9\node_modules\atom-terminal-tab\node_modules\node-pty
 node scripts/install.js

C:\Users\PRIYAR~1\AppData\Local\Temp\apm-install-dir-117726-16708-zbisyb.hgw5o5stt9\node_modules\atom-terminal-tab\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\Priya Ranjan Dubey\AppData\Local\atom\app-1.19.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Priya Ranjan Dubey\AppData\Local\atom\app-1.19.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\PRIYAR~1\AppData\Local\Temp\apm-install-dir-117726-16708-zbisyb.hgw5o5stt9
`-- (empty)

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\Priya Ranjan Dubey\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\Priya Ranjan Dubey\AppData\Local\atom\app-1.19.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\Priya Ranjan Dubey\AppData\Local\atom\app-1.19.0\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\Priya Ranjan Dubey\\AppData\\Local\\atom\\app-1.19.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Priya Ranjan Dubey\\AppData\\Local\\atom\\app-1.19.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\PRIYAR~1\AppData\Local\Temp\apm-install-dir-117726-16708-zbisyb.hgw5o5stt9\node_modules\atom-terminal-tab\node_modules\node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\PRIYAR~1\AppData\Local\Temp\apm-install-dir-117726-16708-zbisyb.hgw5o5stt9\package.json'
npm WARN apm-install-dir-117726-16708-zbisyb.hgw5o5stt9 No description
npm WARN apm-install-dir-117726-16708-zbisyb.hgw5o5stt9 No repository field.
npm WARN apm-install-dir-117726-16708-zbisyb.hgw5o5stt9 No README data
npm WARN apm-install-dir-117726-16708-zbisyb.hgw5o5stt9 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Priya Ranjan Dubey\\AppData\\Local\\atom\\app-1.19.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Priya Ranjan Dubey\\AppData\\Local\\atom\\app-1.19.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Priya Ranjan Dubey\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Priya Ranjan Dubey\\.atom\\.apmrc" "install" "C:\\Users\\PRIYAR~1\\AppData\\Local\\Temp\\d-117726-16708-l98qv7.8ha1fnipb9\\package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.6.10 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.6.10 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PRIYAR~1\AppData\Local\Temp\apm-install-dir-117726-16708-zbisyb.hgw5o5stt9\npm-debug.log
npm ERR! code 1

**Comment by vuki** [comment]
You need Microsoft Visual Studio and Python 2.7 to install this on Windows.

```
gyp ERR! stack Error: Python executable "C:\Users\Priya Ranjan Dubey\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```

**Comment by wec22** [comment]
I have both Visual Studio 2017 installed and have installed python 2.7 and am still getting an error


> node-pty@0.6.10 install C:\Users\elica\AppData\Local\Temp\apm-install-dir-11787-18436-16c4oev.0nw1bjfw29\node_modules\atom-terminal-tab\node_modules\node-pty
> node scripts/install.js


C:\Users\elica\AppData\Local\Temp\apm-install-dir-11787-18436-16c4oev.0nw1bjfw29\node_modules\atom-terminal-tab\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\elica\AppData\Local\atom\app-1.19.6\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\elica\AppData\Local\atom\app-1.19.6\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\elica\AppData\Local\Temp\apm-install-dir-11787-18436-16c4oev.0nw1bjfw29\node_modules\atom-terminal-tab\node_modules\node-pty\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\elica\AppData\Local\Temp\apm-install-dir-11787-18436-16c4oev.0nw1bjfw29\node_modules\atom-terminal-tab\node_modules\node-pty\build\binding.sln]
C:\Users\elica\AppData\Local\Temp\apm-install-dir-11787-18436-16c4oev.0nw1bjfw29
`-- (empty)


gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\elica\AppData\Local\atom\app-1.19.6\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\elica\\AppData\\Local\\atom\\app-1.19.6\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\elica\\AppData\\Local\\atom\\app-1.19.6\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\elica\AppData\Local\Temp\apm-install-dir-11787-18436-16c4oev.0nw1bjfw29\node_modules\atom-terminal-tab\node_modules\node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\elica\AppData\Local\Temp\apm-install-dir-11787-18436-16c4oev.0nw1bjfw29\package.json'
npm WARN apm-install-dir-11787-18436-16c4oev.0nw1bjfw29 No description
npm WARN apm-install-dir-11787-18436-16c4oev.0nw1bjfw29 No repository field.
npm WARN apm-install-dir-11787-18436-16c4oev.0nw1bjfw29 No README data
npm WARN apm-install-dir-11787-18436-16c4oev.0nw1bjfw29 No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\elica\\AppData\\Local\\atom\\app-1.19.6\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\elica\\AppData\\Local\\atom\\app-1.19.6\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\elica\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\elica\\.atom\\.apmrc" "install" "C:\\Users\\elica\\AppData\\Local\\Temp\\d-11787-18436-16y2luf.5h853a0pb9\\package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.6.10 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.6.10 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\elica\AppData\Local\Temp\apm-install-dir-11787-18436-16c4oev.0nw1bjfw29\npm-debug.log
npm ERR! code 1

**Comment by TechiePriyaRanjan** [comment]
why one need to install Microsoft Visual Studio for this? also, I've Python installed on my system :)

**Comment by vuki** [comment]
Because this module depends on ptyw which is C module that has to be compiled. You don't have the compiler, hence the error.

https://github.com/v8/v8/wiki/Building-with-Gyp

Also, you have python 3.6 which is not compatible with gyp. You need python 2.7, as the error message clearly states.
