### ISSUE TITLE
Run .bash_profile?

### ISSUE THREAD

**Issue by antonkluev** [jsmecham/atom-terminal-tab#3]
Hi, 
can you please build in a function to run some scripts on start of the terminal? 
I have my own styles saved in .bash_profile.
Thanks.

**Comment by acondiff** [comment]
@antonkluev Atom terminal tab uses xterm which reads `~/.bashrc`. Put all your `.bash_profile` file in there or import it into `.bashrc' like this:
```
# ~/.bashrc
if [ -f ~/.bash_profile ]; then
  source ~/.bash_profile
fi
``` 

Hope that helps!
