### ISSUE TITLE
Terminal displays "bash-3.2$"

### ISSUE THREAD

**Issue by bgarrant** [jsmecham/atom-terminal-tab#35]
Why does Terminal Tab in Atom display as `bash-3.2$` on my new MBP?  Everywhere else, including in Terminal I see `Bryans-MacBook-Pro:~ username$ `.  Am I missing something?  It seems to work OK but wondering why it says that.

**Comment by bgarrant** [comment]
So does Terminal Tab just run bash directory without using the Terminal app?  Do I need to do anything?

**Comment by daviwil** [comment]
Could be because the shell process is being spawned with an empty environment variable object:

https://github.com/jsmecham/atom-terminal-tab/blob/master/lib/terminal-view.js#L122

**Comment by bgarrant** [comment]
I see that now.  Is that a bug?

**Comment by daviwil** [comment]
I think so, but that's @jsmecham's call.  I just created PR #36 to fix it!

**Comment by bgarrant** [comment]
Even after the pull request change is applied the issue still remains.

![screen shot 2018-01-09 at 1 46 52 pm](https://user-images.githubusercontent.com/2436728/34737241-9646e28c-f543-11e7-8d3e-e040fd74261b.png)

**Comment by bgarrant** [comment]
If I run `bash -l` it gies me the correct value of `Bryans-MacBook-Pro:adkmercy bgarrant$`

**Comment by bgarrant** [comment]
Somehow it is not reading the `~/.bash_profile`

**Comment by bgarrant** [comment]
Fixed in https://github.com/jsmecham/atom-terminal-tab/pull/36
