### ISSUE TITLE
Rename to Atom Terminal Pane?

### ISSUE THREAD

**Issue by jsmecham** [jsmecham/atom-terminal-tab#41]
I've never been a big fan of the name `atom-terminal-tab`. Just that all the good names seemed to have been taken. Considering this add-on is intended to be used as a pane, would it make sense to rename to `atom-terminal-pane`?

My only concern there (and also with `tab`) is that it wouldn't make sense to implement a panel mode with that name. However, I'm not sure I'd ever be interested in making it support panels anyways. The point is to keep this project as simple as possible with reasonable defaults.

Discuss.

**Comment by jsmecham** [comment]
Also, hoping nobody snags the name while under consideration... :)

**Comment by daviwil** [comment]
Yeah, "pane" may confuse things a bit more.  "Tab" seems more accurate since it's a dockable tab, and you basically get what's advertised :)

**Comment by jsmecham** [comment]
Yea, I suppose "pane" doesn't make sense, since panes contain tabs. Atom itself calls them "tabs" so maybe I'm overthinking it.

**Comment by daviwil** [comment]
I dunno, now's the time to question the name since there's a decent chance this package becomes pretty popular this year :)  I can't really think of a better option, especially considering your desire to keep the terminal simple.  The current name definitely conveys that it's a single-focus component rather than a fancy terminal package with a bunch of its own UI.

**Comment by acondiff** [comment]
I agree, the name needs to be changed. I think the word `atom-` in atom-terminal-tab` needs to be dropped to become `terminal-tab` or terminal-pane` or something similar. Atom is implied because you are installing the plugin from Atom itself.

**Comment by daviwil** [comment]
I can certainly agree with a change to "terminal-tab"!

**Comment by daviwil** [comment]
Leaving this here just in case: http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/

```
apm publish --rename <new_name>`
```

**Comment by jsmecham** [comment]
I like it.

**Comment by jsmecham** [comment]
Done.

**Comment by daviwil** [comment]
Sweet!  The old package URL redirects to the new one.  May still want to change the link in the description field of this repo.
