### ISSUE TITLE
bash-3.2$ again

### ISSUE THREAD

**Issue by bgarrant** [jsmecham/atom-terminal-tab#42]
Now with 0.3.3 something broke again.  Now getting `bash-3.2$` on my MBP

**Comment by bgarrant** [comment]
The background color is also no longer matching on 0.3.3.  0.3.2 was working great

**Comment by bgarrant** [comment]
@jsmecham do you see this as well?

**Comment by daviwil** [comment]
I think renaming the package broke all the settings, I can send a PR real quick.

**Comment by jsmecham** [comment]
I'm already on it. New release coming.

**Comment by daviwil** [comment]
Cool!

**Comment by jsmecham** [comment]
Try now with v0.3.4.

**Comment by bgarrant** [comment]
All is good again.  Thanks so much guys

**Comment by daviwil** [comment]
That's what you call agile development ;)

**Comment by bgarrant** [comment]
This plugin is the single one that keeps me in Atom.  No joke.  I love moving my terminal around and having it docked next to others.  Great job everyone.
