### ISSUE TITLE
Small Glitch if Terminal Left Open

### ISSUE THREAD

**Issue by bgarrant** [jsmecham/atom-terminal-tab#46]
When Terminal Tab is initial launched it is perfect:

![screen shot 2018-01-10 at 6 45 01 pm](https://user-images.githubusercontent.com/2436728/34801385-75daa4ae-f636-11e7-8002-2095e935b3aa.png)

Then you quit Atom with Terminal Tab open, reopen Atom and you get:

![screen shot 2018-01-10 at 6 46 11 pm](https://user-images.githubusercontent.com/2436728/34801407-8f7fd870-f636-11e7-837c-c6d00e158652.png)

**Comment by bgarrant** [comment]
If you close the Terminal Tab before exit of Atom all is fine.

**Comment by daviwil** [comment]
@jsmecham's upcoming improvements to terminal initialization will probably resolve this

**Comment by bgarrant** [comment]
Sounds great. Just wanted to report the bug. This is a minor one. Thanks again.

**Comment by bgarrant** [comment]
Sorry as I think I also mentioned this same thing in https://github.com/jsmecham/atom-terminal-tab/issues/55

**Comment by bgarrant** [comment]
@daviwil @jsmecham Have you had a chance to look at this?  I am in and out of Atom a lot and it fails when I open every time unless I close the terminal first.  It would be great if it would disconnect and show the correct command prompt again when you reopen.

before closing:

![screen shot 2018-02-01 at 10 57 48 am](https://user-images.githubusercontent.com/2436728/35688426-26e27074-073f-11e8-9f4f-251fc14be453.png)

after closing and reopening

![screen shot 2018-02-01 at 10 58 08 am](https://user-images.githubusercontent.com/2436728/35688441-3031439e-073f-11e8-8474-c18b9af07c0e.png)

I use two terminals at all time (one local, one remote) so this feature would be huge.  Thanks so much for consideration...

**Comment by bgarrant** [comment]
In a perfect world the tabs would reopen and just both have `Bryans-MacBook-Pro:perufcu bgarrant$`
