### ISSUE TITLE
.bashrc is ignored

### ISSUE THREAD

**Issue by w8jcik** [jsmecham/atom-terminal-tab#49]
No functions, aliases and environmental variables that are present in my `.bashrc` are accessible from the `terminal-tab` terminal.

It is working again when I put a space into *Shell Application Arguments* in the preferences of the package, what probably removes `--login` parameter from the bash command.

I don't think it is intended behavior. People usually want their `.bashrc` and `.bash_profile` to be sourced in the same way across different terminals and by default.

As far as I know the `--login` parameter should result in sourcing them, right? For some reason it doesn't. At least not on my system.

It was working fine something like week ago, when the package was at version `0.2.2`.

### Package versions
* terminal-tab 0.4.0
* atom 1.23.3
* electron 1.6.15
* electron chrome 56.0.2924.87
* electron node 7.4.0

(Arch Linux)

**Comment by daviwil** [comment]
Yep, `--login` should cause them to be sourced.   There might be a problem in how the default setting gets used, I'll look into it!

**Comment by w8jcik** [comment]
No longer an issue as of version 0.5.0.
