### ISSUE TITLE
Font size matches editor or not depending on how you open terminals

### ISSUE THREAD

**Issue by w8jcik** [jsmecham/atom-terminal-tab#54]
I am using non-standard font size, which you can reproduce by pressing Ctrl+0, then Ctrl+-.

If there is no terminals open, after opening the first terminal the font size doesn't match the font-size of the editor:

![screenshot_2018-01-25_23-37-20](https://user-images.githubusercontent.com/3964620/35416276-dc28af46-0228-11e8-97e2-99231abb3340.png)

Just after restarting atom, the font size changes, now it matches the font size of the editor:

![screenshot_2018-01-25_23-38-29](https://user-images.githubusercontent.com/3964620/35416277-df917618-0228-11e8-8e9a-0a440881a8bc.png)

There is one more strange behavior related to this. After running without terminals, the first has big font, the second tab also, but when I switch back to the first one it 1) gets proper font size 2) doesn't cover full area:

![screenshot_2018-01-25_23-46-35](https://user-images.githubusercontent.com/3964620/35416652-2b18c07c-022a-11e8-8848-49d479981cf4.png)

### Package versions
* terminal-tab 0.4.0
* atom 1.23.3
* electron 1.6.15
* electron chrome 56.0.2924.87
* electron node 7.4.0

(Arch Linux)

**Comment by jsmecham** [comment]
This should be resolved with the 0.5.0 release as we now observe for font changes (font family, font size) and update when they do change. Please test and feel free to reopen this if you are still seeing the issue.

**Comment by w8jcik** [comment]
It works like a charm now :) Thanks.
