### ISSUE TITLE
Keybinding clashes with "reopen last item"

### ISSUE THREAD

**Issue by alexrussell** [jsmecham/atom-terminal-tab#6]
Atom has a keybinding already on `cmd+shift+t` for reopen last item, but this package overrides that as it is a more specific selector (well, loaded after, so more specific by default I presume) and the 'settings' doesn't have a way to turn off the keybindings like it does for other packages.

Any chance of changing the keybinding or allowing users to reassign/turn off?

**Comment by jsmecham** [comment]
My next focus of work is going to be on key bindings and compatibility. See #66 where I will be tracking this work. Thanks!

**Comment by jsmecham** [comment]
Closing this, but it is not forgotten. Work is being tracked in #66 and will be progressing shortly.
