### ISSUE TITLE
Scrollbar at the left side

### ISSUE THREAD

**Issue by Positive07** [jsmecham/atom-terminal-tab#7]
This is most likely a styling issue, but it looks odd
![captura de pantalla 2017-05-18 18 03 17](https://cloud.githubusercontent.com/assets/1095969/26223419/530c9970-3bf4-11e7-9e3a-12b605d55e75.png)

On a different topic, there is an error in the Developer Tools console saying:
```
You did not pass the `focus` argument in `Terminal.prototype.open()`.
The `focus` argument now defaults to `true` but starting with xterm.js 3.0 it will default to `false`.
```

And some other issue that has to do with docks losing focus when they are clicked (but that is Atom's fault I would guess)

System: Windows 10 64bits Atom 1.18 beta 0

**Comment by mhnavarro** [comment]
Happens in linux too

**Comment by jsmecham** [comment]
This should be fixed (only tested on Mac) in the forthcoming 0.2.1 release.

**Comment by sniperrifle2004** [comment]
I am experiencing (something like?) this on linux running atom 1.22.1 with atom-terminal-tab 0.2.2. The scroll bar jumps to the left when the terminal tab gains focus (Though it appears to be the viewport that is actually shrinking). If the area is affected in certain ways (scroll back buffer cleared at least (for example by less)) it returns to its proper position until focus is lost and then gained again.
