### ISSUE TITLE
Terminals not persinting working directory

### ISSUE THREAD

**Issue by w8jcik** [jsmecham/atom-terminal-tab#71]
- Open two different projects in one window
- Open a file from each of them
- Invoke terminal for each of the files
  - They get correct working directories, two different ones
- Restart Atom
  - Two terminals are restored, but with the same working directory

`terminal-tab 0.5.4`

**Comment by jsmecham** [comment]
This should be fixed in 4a5c8b6d63aac7ec4dac64406013c3f6e84b22ce. Please test v0.5.6 and let me know if you are still seeing this issue. Thanks!
