### ISSUE TITLE
Ignores Shell Path - opens default shell

### ISSUE THREAD

**Issue by MarMun** [jsmecham/atom-terminal-tab#75]
Windows 10. I try to have...

`C:\Program Files\Git\bin\bash.exe`

... as my terminal but ... 

`C:\WINDOWS\system32\cmd.exe`

... gets opened instead.

**Comment by jsmecham** [comment]
Can you give v0.5.5 a try? I inadvertently broke this in v0.5.4.

**Comment by jsmecham** [comment]
I'm going to close this since I have not heard back. Please feel free to reopen if this is still an issue on v0.5.4 or greater.
