### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by danielbayley** [jsmecham/atom-terminal-tab#8]
MacOS Sierra 10.12.5
Atom 1.18.0-beta0
apm  1.18.1

~~~ sh
apm i atom-terminal-tab
Installing atom-terminal-tab to /Users/Dan/Library/Application Support/Atom/packages ✗
~~~

\> node-pty@0.6.5 install /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117418-46194-1269cvw.7bdpshsemi/node_modules/atom-terminal-tab/node_modules/node-pty
\> node scripts/install.js

  CXX(target) Release/obj.target/pty/src/unix/pty.o
/private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117418-46194-1269cvw.7bdpshsemi
└── (empty)

2017-05-18 23:50:23.348 xcodebuild[46216:7399968] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/WakaTime.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-05-18 23:50:23.350 xcodebuild[46216:7399968] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
clang: error: no such file or directory: 'Support/Atom/.node-gyp/.node-gyp/iojs-1.3.15/include/node'
clang: error: no such file or directory: 'Support/Atom/.node-gyp/.node-gyp/iojs-1.3.15/src'
clang: error: no such file or directory: 'Support/Atom/.node-gyp/.node-gyp/iojs-1.3.15/deps/uv/include'
clang: error: no such file or directory: 'Support/Atom/.node-gyp/.node-gyp/iojs-1.3.15/deps/v8/include'
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117418-46194-1269cvw.7bdpshsemi/node_modules/atom-terminal-tab/node_modules/node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117418-46194-1269cvw.7bdpshsemi/package.json'
npm WARN apm-install-dir-117418-46194-1269cvw.7bdpshsemi No description
npm WARN apm-install-dir-117418-46194-1269cvw.7bdpshsemi No repository field.
npm WARN apm-install-dir-117418-46194-1269cvw.7bdpshsemi No README data
npm WARN apm-install-dir-117418-46194-1269cvw.7bdpshsemi No license field.
npm ERR! Darwin 16.6.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Dan/Library/Application Support/Atom/.apm/.apmrc" "--userconfig" "/Users/Dan/Library/Application Support/Atom/.apmrc" "install" "/private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/d-117418-46194-ngg2st.ed0246ajor/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.6.5 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.6.5 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/rg/4lc94q1x1_xd89qsnjdkgsjw0000gn/T/apm-install-dir-117418-46194-1269cvw.7bdpshsemi/npm-debug.log
npm ERR! code 1

**Comment by emersion** [comment]
This is an issue with [`node-pty`](https://github.com/Tyriar/node-pty).
