### ISSUE TITLE
Copy/paste

### ISSUE THREAD

**Issue by emersion** [jsmecham/atom-terminal-tab#9]
It's not possible to copy or paste from/to the terminal.

It would be useful (1) to have at least an item to do so in the right-click menu, and (2) to bind a keyboard shortcut (something like <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>/<kbd>V</kbd>).

**Comment by jsmecham** [comment]
Copy and paste works for me on Mac. What platform are you using?

**Comment by emersion** [comment]
I'm using Linux, but I bet there's the same issue on Windows. macOS is special because of the command key - the <kbd>Ctrl</kbd> + <kbd>C</kbd> shortcut is not a conflict between "stop the current process" and "copy text".

Most terminal emulators solve this by re-binding the copy command to <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>, and keep <kbd>Ctrl</kbd> + <kbd>C</kbd> to stop the current process.

**Comment by HotelCalifornia** [comment]
I just started running into this error- up until today it worked just fine for me (Mac OS X 10.12.5)

**Comment by danielbayley** [comment]
I can't copy/paste on mac either…

macOS 10.12.6
Atom 1.19.0-beta5
atom-terminal-tab 0.2.2

**Comment by danielbayley** [comment]
@jsmecham I wonder if there could be a way to turn the panel into an actual `atom-text-editor`?

**Comment by bennypowers** [comment]
I'm unable to select text in terminal on my mac

**Comment by jsmecham** [comment]
I'm going to close this since many things have changed since this was last updated and I have not experienced the issue in my testing. Please feel free to reopen if the problem persists after testing with the just released 0.5.0 version.

**Comment by danielbayley** [comment]
Following on from my comment above… I maintain that the panel output should be an `atom-text-editor`, especially now that they can have a [`readonly`](https://github.com/atom/atom/pull/16294) attribute.
