### ISSUE TITLE
Open praise for atom-terminal-tab

### ISSUE THREAD

**Issue by lukepighetti** [jsmecham/atom-terminal-tab#91]
Yeah I know this isn't supposed to be here, but here goes.

The top downloaded terminals are absolute garbage. They can't handle resizing in nano, they break selections on newline, they are slow, and they do not fit with the Atom aesthetic.

atom-terminal-tab solves all of those problems, and it does so quietly with very few options.

WELL. DONE.

If you continue to maintain this, I hope you focus on performance. This terminal does NOT need more features. There are plenty of "full featured" (read: horrible) terminal packages out there.

**Comment by thiagola92** [comment]
> Yeah I know this isn't supposed to be here

I was searching any place to praise this package, i was thinking about doing the same.

This package is exactly what i wanted:  
* Simple
* Beautiful (blend perfectly with Atom)

GREAT JOB!

**Comment by jsmecham** [comment]
Thank you for the kind words :)
