### ISSUE TITLE
Broken when using Atom v1.28.0 (release; non-beta)

### ISSUE THREAD

**Issue by RedcoatAsher** [jsmecham/atom-terminal-tab#96]
Updated Atom from v1.27.x -> v1.28.0 and now the terminal-tab extension package has stopped working :/

I have tried disabling, uninstalling, and reinstalling... no dice.

**IMPORTANT** I am not using a beta version like Issue #90; this is for the prod release version of Atom.

**Comment by SReject** [comment]
Click the red "bug" icon in bottom right of atom; in the page that pops up, click the "Rebuild" button
